# Generated by Django 3.2.18 on 2023-04-20 06:56

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU', verbose_name='Номер телефона')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер бокса')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Ширина')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Длина')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Высота потолка')),
                ('temperature', models.IntegerField(blank=True, null=True, verbose_name='Температура на складе')),
                ('occupied', models.BooleanField(default=False, verbose_name='Бокс занят')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Адрес')),
                ('picture', models.ImageField(upload_to='', verbose_name='Фото склада')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_period', models.IntegerField(choices=[(3, '3 months'), (6, '6 months'), (12, '12 months')], verbose_name='Период аренды')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR код для получения вещей')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий по аренде')),
                ('address', models.TextField(verbose_name='Адрес клиента')),
                ('delivery_needed', models.BooleanField(default=False, verbose_name='Нужна доставка')),
                ('measurement_needed', models.BooleanField(default=False, verbose_name='Нужен замер')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала аренды')),
                ('pickup_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания аренды по тарифу')),
                ('rental_period_price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость хранения по тарифу')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения аренды')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Хранение завершено')),
                ('is_rental_extended', models.BooleanField(default=False, verbose_name='Аренда продлена')),
                ('utilize_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дата утилизации вещей')),
                ('deadline_overdue', models.IntegerField(blank=True, null=True, verbose_name='Дни превышения срока аренды')),
                ('extra_payment', models.IntegerField(blank=True, null=True, verbose_name='Сумма для оплаты просрочки')),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='storage.box', verbose_name='Бокс')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storage.storage', verbose_name='Склад'),
        ),
        migrations.AlterUniqueTogether(
            name='box',
            unique_together={('storage', 'number')},
        ),
    ]
