# Generated by Django 3.2.18 on 2023-04-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='picture',
            field=models.ImageField(upload_to='storage', verbose_name='Фото склада'),
        ),
    ]
