# Generated by Django 3.2.18 on 2023-04-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_storage_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='big_picture',
            field=models.ImageField(blank=True, upload_to='storage', verbose_name='Фото склада большое'),
        ),
    ]
