# Generated by Django 3.2.18 on 2023-04-20 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_storage_big_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
